In [1]:
import pandas as pd
data = pd.read_csv('ensemble_stats.csv')
data.head()

,TAXID,GENUSNAME,SPECIESNAME,STRAIN,DBNAME,FILEPATH,chromosome_count,avg_length_chromosomes,max_length_chromosomes,min_length_chromosomes,...,max_length_contig,min_length_contig,mtDNA_count,avg_length_mtDNA,max_length_mtDNA,min_length_mtDNA,plasmid_count,avg_length_plasmids,max_length_plasmids,min_length_plasmids
0,4829,absidia,glauca,NaN,ENSEMBLE,/u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Absi...,0,0,0,0,...,1790682,221,0,0,0,0,0,0,0,0
1,245562,acidomyces,richmondensis,NaN,ENSEMBLE,/u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Acid...,0,0,0,0,...,256309,1017,0,0,0,0,0,0,0,0
2,766039,acidomyces,richmondensis bfw,NaN,ENSEMBLE,/u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Acid...,0,0,0,0,...,219268,357,0,0,0,0,0,0,0,0
3,857340,acremonium,chrysogenum atcc 11550,NaN,ENSEMBLE,/u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Acre...,0,0,0,0,...,893296,315,1,27766,27766,27766,0,0,0,0
4,597362,agaricus,bisporus var. burnettii jb137-s8,NaN,ENSEMBLE,/u/home/a/akarlsbe/scratch/fungi/ENSEMBLE/Agar...,0,0,0,0,...,3023116,509,0,0,0,0,0,0,0,0

In [3]:
import sqlite3
select * from speciesdb where dbname = "ENSEMBLE";

UsageError: Line magic function `%sql` not found.